/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 1 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_1 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 2 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_2 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 3 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_3 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 4 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_4 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 5 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_5 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 6 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_6 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 7 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_7 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 8 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_8 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 9 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_9 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 10 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_10
sleep 0.5
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 11 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_11 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 12 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_12 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 13 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_13 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 14 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_14 & 
/Users/davidenard/Dropbox/exdef_folder/shuffle_sweep_script.pl /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/ /Users/davidenard/Dropbox/exdef_folder/valid_file.txt 15 /Users/davidenard/Dropbox/exdef_folder/ensembl_gene_coords_v69 all_ihsfreqabs_ranks 1000kb 100 && gzip -f /Users/davidenard/Dropbox/exdef_folder/shuffled_sweep_files/*_15 & 
